language: cpp
os: linux
dist: bionic
compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
      - texlive
      - texlive-generic-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - texlive-font-utils
      - ghostscript

linux-ppc64le: &linux-ppc64le
  os: linux-ppc64le
  env:
    - OS_NAME="linux-ppc64le"
  addons:
    apt:
      update: true
      packages:
        - texlive
        - texlive-generic-recommended
        - texlive-extra-utils
        - texlive-latex-extra
        - texlive-font-utils
        - ghostscript
        - libxml2-utils
        - cmake
        - cmake-data

linux-s390x: &linux-s390x
  os: linux
  arch: s390x
  dist: bionic
  env:
    - OS_NAME="linux-s390x"
  addons:
    apt:
      update: true
      packages:
        - texlive
        - texlive-generic-recommended
        - texlive-extra-utils
        - texlive-latex-extra
        - texlive-font-utils
        - ghostscript
        - libxml2-utils
        - cmake
        - cmake-data
        - qt5-default

jobs:
  include:
    - <<: *linux-ppc64le
      compiler: gcc
    - <<: *linux-ppc64le
      compiler: clang
    - <<: *linux-s390x
      compiler: gcc
    - <<: *linux-s390x
      compiler: clang

before_script:
  - |
    if [ ! "${OS_NAME}" == "linux-ppc64le" ] && [ ! "${OS_NAME}" == "linux-s390x" ]; then
      printf "[requires]
      libxml2/2.9.9
      libiconv/1.15" >> conanfile.txt;
    fi;
  - if [ ! "${OS_NAME}" == "linux-ppc64le" ] && [ ! "${OS_NAME}" == "linux-s390x" ]; then
      pip install --quiet --user conan;
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
      conan install . -g virtualrunenv --build missing --update;
      source activate_run.sh;
    fi;

script:
  - mkdir build
  - cd build
  - cmake --version;
  - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
  - make
  - make tests
  - make docs
