language: cpp
os:
    - linux-ppc64le
    - linux
dist: xenial
compiler:
  - gcc
  - clang
sudo: required

cache:
    directories:
        - $HOME/.cache/pip
        - /Library/TeX/texbin
        - /Users/travis/Library/TeX/texbin
    before_cache:
        - rm -f $HOME/.cache/pip/log/debug.log

addons:
    apt:
        update: true
        packages:
            - texlive
            - texlive-generic-recommended
            - texlive-extra-utils
            - texlive-latex-extra
            - texlive-font-utils
            - ghostscript
            - libxml2-utils
            - cmake
            - cmake-data

jobs:
    include:
        - os: osx
          compiler: clang

before_script:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        pip install --quiet -U conan;
        export HOMEBREW_NO_AUTO_UPDATE=1;
        brew install ghostscript;

        if [ ! -d "/Library/TeX/texbin" ]; then
            travis_wait brew cask install mactex-no-gui;
            curl -O -L http://mirrors.ctan.org/support/epstopdf.zip;
            unzip epstopdf.zip;
            cd epstopdf;
            chmod a+x epstopdf.pl;
            mv epstopdf.pl epstopdf;
            mkdir -p /Users/travis/Library/TeX/texbin/;
            mv epstopdf /Users/travis/Library/TeX/texbin/;
            cd .. ;
            rm -rf epstopdf*;
        fi;
        export PATH=/Users/travis/Library/TeX/texbin:/Library/TeX/texbin:$PATH;

        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
        printf "[requires] \nlibxml2/2.9.8@bincrafters/stable \nQt/5.11.1@bincrafters/stable" >> conanfile.txt;
        conan install . -g virtualrunenv;
        source activate_run.sh;
      fi;

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
